### ISSUE TITLE
Implementation of EEG pipeline

### ISSUE THREAD

**Issue by sebastientourbier** [connectomicslab/connectomemapper3#6]
**First thoughts**
* Design/first sketch of the new EEG pipeline 
* Function to load Cartool / EEGlab / Fieldtrip inverse solutions as input
* Implement the interface to compute single source dipoles per ROI based on SVD decomposition [Rubega et al. 2018] using pycartool
* Computes diverse common functional connectivity metrics (Imaginary coherence, ...) using [MNE](https://martinos.org/mne/stable/index.html) 
* Implement the interface to compute time-varying functional connectivity based on the Granger causality framework and a modified version of the adaptive Kalman filter as proposed in [Pascucci et al. 2019]. This allows to recursively refine time-varying directed connectivity estimates with structural connectivity. 

> [Rubega et al. 2018] Rubega, M.; Carboni, M.; Seeber, M.; Vulliemoz, S.; and Michel, C. M. Estimating EEG source dipoles based on singular-value decomposition for connectivity analysis. 2018. [paper](https://link.springer.com/article/10.1007%2Fs10548-018-0691-2)

> [Pascucci et al. 2019] Pascucci D.; Rubega M.; Hagmann P.; Plomp G. Adaptive filtering with anatomical priors: Integrating structural and effective connectivity. [OHBM 19 abstract](https://ww5.aievolution.com/hbm1901/index.cfm?do=abs.viewAbs&abs=3100)

**What need to be answered**
  - [x] How to visualize sources estimated by Cartool in MNE (translation in log file enough?)
  - [x] Check if MNE provides already function to load EEGlab, FieldTrip
  Yes (TO DO: list the functions). 
  - [x]  How Cartool / EGGlab / Fieldtrip / Brainstorm / MNE are saving outputs (BIDS or in-house organization). This will indicate us how to grab the data (cleaned EEG data and LeadField matrix) in the most automatical way.
  - [x]  The determination of a common source space (Freesurfer space might be prefered as we already provide the annotation files for the Lausanne2008 and Lausanne2018 parcellations)
  - [x] Difference between SVD method in [Rubega et al. 2018] and the SVD method implemented in MNE (mode: `pca_flip`) 
  - [x] How to adopt BIDS EEG ([see spec paper](https://www.nature.com/articles/s41597-019-0104-8.pdf))

**To be prepared and implemented**

Note: check in Nipype which MNE interfaces are already implemented which could then be used as they are or as a template for the developement of the MNE-related interfaces (Tasks 5. and 6.)

**Achievement**
  - [x] Task 1
  - [x] Task 2
  - [x] Task 3
  - [x] Task 4
  - [x] Task 5
  - [x] Task 6 
  - [ ] Task 7 
  - [x] Task 8
  - [ ] Task 9 

**Task 1**

Preparation of a sample dataset for development (See https://github.com/connectomicslab/connectomemapper3/issues/6#issuecomment-638753547 for more details)

**Task 2** 

Start the implementation of a simple Nipype workflow that can grab and convert to MNE's internal format the cleaned EEG data and the Lead Field matrix generated by:
* Cartool 
* EEGlab  
* Fieldtrip
*  MNE
*  Brainstorm

**Task 3** 

Implement for each toolbox an interface after the data grabber that converts and stores in MNE format the generated outputs (cleaned EEG data and lead field matrix)
  
*Inputs*
* Cleaned EEG in toolbox format 
* Lead field matrix in toolbox format 
  
*Outputs*
* Cleaned EEG in MNE format 
* Lead field matrix in MNE format 

**Task 4** 

Implement an interface that creates the inverse solutions and transforms the source coordinates into a common source space
  
*Inputs*
* Cleaned EEG in MNE format (channels x time)
* Lead field matrix in MNE format (#sources x channels)
* Transformation from toolbox source coordinates to common space
  
*To be performed*
* Computes inverse solution (sources):
  Source = Lead field matrix x cleaned EEG
* Transform the source coordinates (sources)
 
*Outputs*
* Source time-series
* Source coordinates

**Task 5** 

Check if output sources from the different toolbox are in proper common space

**Task 6** 

Implementation of an interface for estimating ROI dipoles based on Maria's SVD and/or MNE SVD methods.

*Inputs*
* Inverse solution in MNE format
* Parcellation annotation files or parcellation scheme

*Outputs*
* ROI dipoles in MNE format

*To be performed*
* Use MNE function or implementation of Maria's method to create ROI dipoles in MNE format

**Task 7** 

Implementation of an interface for estimating multiple dynamic functional connectome maps

*Inputs*
* ROI dipoles in MNE format
 
*Outputs*
* Dynamic FC maps in .gpickle format 
* Dynamic FC maps in .mat format 

*To be performed*
* Computes multiple dynamic functional connectome maps using measure implemented in MNE and pycartool

**Task 8 (Large effort)**

Implementation of EEGPipeline:

* Organisation of pipeline and stages (for configuration and ouput inspection with bidsappmanager) 

* Implement the stages (config parameters, create_worflow, inpsect_outputs) and modify the existing `cmp/pipelines/EEG.py` to implement the complete workflow

* Implement the GUI components (EEGPipelineUI and all the related stages) for integration in the `cmpbidsappmanager`

* Review bidsapp parser and run.py to take as input the eeg config file

**Task 9**

Documentation:

* Add functionality in the `index.html` page
* Update the `bidsappmanager.html` with EEG in 1) pipeline configuration, 2) run the bidsapp and 3) check stage outputs, 
* Update `outputs.html` page with BIDS-EEG derivatives data produced by CMP

**Comment by sebastientourbier** [comment]
Check if MNE provides already function to load EEGlab, FieldTrip

**Comment by sebastientourbier** [comment]
Code providing cartool I/O and functions in python:
* https://github.com/Functional-Brain-Mapping-Laboratory/PyCartool/tree/master/pycartool
* https://pycartool.readthedocs.io/en/latest/?badge=latest

**Comment by sebastientourbier** [comment]
Investigate head model with MNE

**Comment by sebastientourbier** [comment]
> **What need to be answered**
> 
>     * [ ]  Check if MNE provides already function to load EEGlab, FieldTrip
>       Yes (TO DO: list the functions).
> 
>     * [ ]   How Cartool / EGGlab / Fieldtrip / Brainstorm / MNE are saving outputs (BIDS or in-house organization). This will indicate us how to grab the data (cleaned EEG data and LeadField matrix) in the most automatical way.
> 
>     * [ ]   The determination of a common source space (Freesurfer space might be prefered as we already provide the annotation files for the Lausanne2008 and Lausanne2018 parcellations)
> 
>     * [ ]  Difference between SVD method in [Rubega et al. 2018] and the SVD method implemented in MNE (mode: `pca_flip`)
> 
>     * [ ]  How to adopt BIDS EEG ([see spec paper](https://www.nature.com/articles/s41597-019-0104-8.pdf))
> 
> 
> **To be implemented**
> 
>     1. A simple workflow that can grab and convert the MNE internal format the cleaned EEG data and the Lead Field matrix generated by:
> 
> 
>     * [ ]   Cartool
> 
>     * [ ]  EEGlab
> 
>     * [ ]  Fieldtrip
> 
>     * [ ]   MNE
> 
>     * [ ]   Brainstorm
> 
> 
>     1. Implement for each toolbox an interface after the data grabber that converts and stores in MNE format the generated outputs (cleaned EEG data and lead field matrix)
> 
> 
> _Inputs_
> 
>     * Cleaned EEG in toolbox format
> 
>     * Lead field matrix in toolbox format
> 
> 
> _Outputs_
> 
>     * Cleaned EEG in MNE format
> 
>     * Lead field matrix in MNE format
> 
> 
>     1. Implement an interface that creates the inverse solutions and transforms the source coordinates into a common source space
> 
> 
> _Inputs_
> 
>     * Cleaned EEG in MNE format (channels x time)
> 
>     * Lead field matrix in MNE format (#sources x channels)
> 
>     * Transformation from toolbox source coordinates to common space
> 
> 
> _To be performed_
> 
>     * Computes inverse solution (sources):
>       Source = Lead field matrix x cleaned EEG
> 
>     * Transform the source coordinates (sources)
> 
> 
> _Outputs_
> 
>     * Source time-series
> 
>     * Source coordinates
> 
> 
>     1. Check if output sources from the different toolbox are in proper common space
> 
> 
>     * [ ]   Cartool
> 
>     * [ ]  EEGlab
> 
>     * [ ]  Fieldtrip
> 
>     * [ ]   MNE
> 
>     * [ ]   Brainstorm
> 
> 
>     1. Implementation of an interface for estimating ROI dipoles based on Maria's SVD and/or MNE SVD methods.
> 
> 
> _Inputs_
> 
>     * Inverse solution in MNE format
> 
>     * Parcellation annotation files or parcellation scheme
> 
> 
> _Outputs_
> 
>     * ROI dipoles in MNE format
> 
> 
> _To be performed_
> 
>     * Use MNE function or implementation of Maria's method to create ROI dipoles in MNE format
> 
> 
>     1. Implementation of an interface for estimating multiple dynamic functional connectome maps
> 
> 
> _Inputs_
> 
>     * ROI dipoles in MNE format
> 
> 
> _Outputs_
> 
>     * Dynamic FC maps in .gpickle format
> 
>     * Dynamic FC maps in .mat format
> 
> 
> _To be performed_
> 
>     * Computes multiple dynamic functional connectome maps using measure implemented in MNE and pycartool

Based on our discussion with Joan yesterday

**Comment by sebastientourbier** [comment]
## Preparation of  a sample dataset for development

**Tasks involved**
- [ ] Decision and creation of a common dataset (source data: T1w, EEG, (DWI and fMRI would be great also))
* Estimation of inversion solutions for:
    - [ ] Cartool (proprietary)
    - [ ] EEGlab (open / matlab)
    - [ ] Fieldtrip (open / matlab)
    - [ ] Brainstorm (open / matlab)
    - [ ] MNE (open / python)
* Organization of the different outputs in the dataset:
    - [ ] Cartool (proprietary)
    - [ ] EEGlab (open / matlab)
    - [ ] Fieldtrip (open / matlab)
    - [ ] Brainstorm (open / matlab)
    - [ ] MNE (open / python)

**Example of structure**
    
       ds-example/
        
        README
        CHANGES
        participants.tsv
        dataset_description.json
        
         sub-<subject_label>/
            anat/
                sub-<subject_label>_T1w.nii.gz
                sub-<subject_label>_T1w.json
            ...
            eeg/
               [To be checked in BIDS-EEG]
        
        ...

        derivatives/
            cartool/
                sub-<subject_label>/
                    eeg/
                        [Outputs from cartool]

            eeglab/
                sub-<subject_label>/
                    eeg/
                        [Outputs from eeglab]

            fieldtrip/
                sub-<subject_label>/
                    eeg/
                        [Outputs from fieldtrip]

            mne/
                sub-<subject_label>/
                    eeg/
                        [Outputs from mne]

        ...

**Resources**

* BIDS-EEG: https://www.nature.com/articles/s41597-019-0104-8
* BIDS-EEG derivatives: https://github.com/bids-standard/bids-specification/issues/317

**Comment by sebastientourbier** [comment]
This is link to ohbm brainhack project "Integrate EEG inside CMP3" (ohbm/hackathon2020#214)
